
import React,{useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{Home,HousePlus,Bot,Share2,Compass,FileText,ShieldCheck,Send,UploadCloud,UserRound,Plus,Trash2,LockKeyhole,CheckCircle2,AlertTriangle,Users,MapPin,ChevronRight,Search,Eye,Clock3,ExternalLink,MessageCircle,Sparkles,Baby,HeartHandshake,BriefcaseBusiness,WalletCards,Landmark}from"lucide-react";
import"./styles.css";

const homes=[
{id:"baarn",title:"Nieuwbouw Baarn",city:"Baarn",price:515000,monthly:2260,match:94,confidence:91,label:"A++",img:"https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1600&q=80",why:["Past ruim binnen bandbreedte","Lage energielasten","Sterke financieringskans"]},
{id:"eemnes",title:"Gezinswoning Eemnes",city:"Eemnes",price:675000,monthly:2920,match:87,confidence:83,label:"A",img:"https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1600&q=80",why:["Overwaarde helpt sterk","Goede gezinsmatch","Overbrugging controleren"]},
{id:"bussum",title:"Hoekwoning Bussum",city:"Bussum",price:725000,monthly:3180,match:76,confidence:74,label:"B",img:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=80",why:["Financieel mogelijk onder voorwaarden","Lease verlaagt score","Werkgeversverklaring ontbreekt"]},
{id:"laren",title:"Vrijstaand Laren",city:"Laren",price:925000,monthly:4050,match:48,confidence:41,label:"A",img:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80",why:["Buiten huidige bandbreedte","Hoge maandlast","Meer eigen geld nodig"]}
];

const erik={
 firstName:"Erik",lastName:"van Slooten",birthDate:"1982-04-12",age:44,nationality:"Nederlands",
 maritalStatus:"Gehuwd",maritalProperty:"Beperkte gemeenschap",partner:true,partnerName:"Partner",partnerAge:42,
 children:true,childCount:2,childAges:"9, 11",coParenting:false,alimony:false,childcare:0,
 workStatus:"Vast contract",employer:"La Fourchette",role:"Chef-kok",income:72800,partnerIncome:57600,
 holidayPay:true,thirteenthMonth:true,bonus:3000,overtime:13000,probation:false,
 pensionAge:67,pensionIncome:0,aowExpected:true,partnerPension:0,pensionDrop:"Onbekend",
 cash:85000,investments:12000,crypto:0,studyDebt:0,loans:25000,creditcard:0,leaseMonthly:550,bkr:"Positieve registratie",
 address:"Laarderweg 23, Eemnes",homeValue:642000,woz:596000,mortgageLeft:418000,sellingCosts:21000,saleStatus:"Nog niet verkocht",mortgageMonthly:1780,rate:3.8,energyLabel:"A",
 places:"Eemnes, Baarn, Bussum, Laren, Hilversum",radius:20,homeType:"Hoekwoning / gezinswoning",rooms:5,garden:true,garage:false,energy:"A of beter"
};

const blank={...erik,firstName:"Nieuwe",lastName:"Koper",age:34,birthDate:"1992-01-01",maritalStatus:"Alleenstaand",partner:false,partnerName:"",partnerAge:0,children:false,childCount:0,childAges:"",income:52000,partnerIncome:0,cash:35000,investments:0,loans:0,leaseMonthly:0,bkr:"Onbekend",address:"",homeValue:0,woz:0,mortgageLeft:0,sellingCosts:0,saleStatus:"Geen huidige woning"};

const starter={...blank,firstName:"Starter",lastName:"Demo",income:48000,cash:22000,places:"Baarn, Hilversum, Amersfoort",homeType:"Appartement",rooms:3};
const zzp={...blank,firstName:"ZZP",lastName:"Demo",workStatus:"ZZP",income:84000,cash:65000,age:39,places:"Laren, Bussum, Hilversum"};

const initialDocs=[
{id:1,name:"Identiteitsbewijs",type:"Identiteit",status:"verified",progress:100,impact:4},
{id:2,name:"Laatste 3 salarisstroken",type:"Inkomen",status:"missing",progress:0,impact:8,required:3,uploaded:0},
{id:3,name:"Werkgeversverklaring",type:"Inkomen",status:"review",progress:65,impact:6},
{id:4,name:"Bankafschrift eigen middelen",type:"Eigen geld",status:"verified",progress:100,impact:5},
{id:5,name:"Hypotheekoverzicht huidige woning",type:"Eigen woning",status:"verified",progress:100,impact:7},
{id:6,name:"Woningwaarde onderbouwing",type:"Overwaarde",status:"review",progress:72,impact:9},
{id:7,name:"Taxatierapport huidige woning",type:"Eigen woning",status:"missing",progress:0,impact:10},
{id:8,name:"Energielabel rapport",type:"Eigen woning",status:"missing",progress:0,impact:5},
{id:9,name:"Bonus/13e maand bewijs",type:"Inkomen",status:"missing",progress:0,impact:3}
];

function euro(n){return"€ "+Math.round(Number(n)||0).toLocaleString("nl-NL")}
function short(n){return"€ "+Math.round((Number(n)||0)/1000)+"k"}
function clamp(v){return Math.max(0,Math.min(100,Math.round(v)))}
function level(v){return v>=82?"green":v>=62?"yellow":"red"}
function equity(b){return Math.max(0,(+b.homeValue||0)-(+b.mortgageLeft||0)-(+b.sellingCosts||0))}
function usable(b){return Math.round(equity(b)*.82)}
function docScore(docs){return Math.round(docs.reduce((s,d)=>s+d.progress,0)/docs.length)}
function hasDoc(docs,name){return docs.find(d=>d.name.toLowerCase().includes(name))?.progress>=100}
function budget(b,docs){
 const income=(+b.income||0)+(+b.partnerIncome||0)+(+b.bonus||0)+(b.thirteenthMonth?((+b.income||0)/12):0);
 const penalty=(+b.leaseMonthly||0)*180+(+b.loans||0)*1.15+(+b.studyDebt||0)*.55+(docScore(docs)<70?25000:0)+(b.saleStatus==="Nog niet verkocht"?35000:0);
 return Math.round(income*4.35+(+b.cash||0)*.82+(+b.investments||0)*.55+usable(b)-penalty);
}
function score(b,docs){
 const ds=docScore(docs), bud=budget(b,docs), eq=equity(b);
 const personal=(b.maritalStatus&&b.age&&b.nationality?94:58);
 const family=(b.children?78+(b.childCount?10:0):92);
 const financial=clamp(50+(bud>700000?22:bud>550000?13:5)-(b.leaseMonthly>0?7:0)-(b.loans>0?5:0)-(b.bkr==="Negatieve registratie"?18:0));
 const homeReliability=clamp((b.address?25:0)+(b.homeValue?20:0)+(hasDoc(docs,"taxatie")?30:0)+(hasDoc(docs,"energielabel")?15:0)+(hasDoc(docs,"hypotheekoverzicht")?10:0));
 const home=clamp((eq>180000?76:eq>80000?62:35)+homeReliability*.22);
 const pensionRisk=(b.age>=57||b.workStatus.includes("Pensioen")||b.workStatus.includes("Bijna"))?((+b.pensionIncome||0)>25000?5:-8):0;
 const confidence=clamp(ds*.36+personal*.14+financial*.18+home*.20+family*.08+pensionRisk);
 const atlas=clamp(financial*.27+ds*.20+home*.22+confidence*.21+family*.10);
 return{atlas,confidence,personal,family,financial,home,homeReliability,docs:ds,budget:bud,equity:eq,usable:usable(b)}
}
function adjustHome(h,s){return{...h,match:clamp(h.match+(s.atlas-84)*.22),confidence:clamp(h.confidence+(s.confidence-84)*.18)}}
function emptyDocs(){return initialDocs.map(d=>({...d,status:"missing",progress:0,uploaded:d.required?0:undefined}))}

function Badge({value,children}){return <span className={"badge "+level(value)}>{children}</span>}
function Bar({value}){return <div className="bar"><span className={level(value)} style={{width:clamp(value)+"%"}}/></div>}
function Header({kicker,title,text}){return <div className="header"><span>{kicker}</span><h2>{title}</h2><p>{text}</p></div>}
function Field({label,value,onChange,type="text",prefix}){return <label className="field"><span>{label}</span><div>{prefix&&<small>{prefix}</small>}<input type={type} value={value} onChange={e=>onChange(type==="number"?Number(e.target.value):e.target.value)}/></div></label>}
function Select({label,value,onChange,options}){return <label className="field"><span>{label}</span><div><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></div></label>}
function Toggle({label,checked,onChange}){return <button className={checked?"toggle on":"toggle"} onClick={()=>onChange(!checked)}><span>{checked?<CheckCircle2 size={17}/>:<span className="dot"/>}</span>{label}</button>}

function App(){
 const[page,setPage]=useState("cockpit"),[buyer,setBuyer]=useState(erik),[docs,setDocs]=useState(initialDocs),[homeId,setHomeId]=useState("baarn"),[wizard,setWizard]=useState(0),[showNew,setShowNew]=useState(false);
 const s=useMemo(()=>score(buyer,docs),[buyer,docs]);
 const selected=adjustHome(homes.find(h=>h.id===homeId),s);
 const update=(k,v)=>setBuyer({...buyer,[k]:v});
 const createProfile=(kind)=>{setBuyer(kind==="starter"?starter:kind==="zzp"?zzp:blank);setDocs(kind==="doorstromer"?initialDocs:emptyDocs());setShowNew(false);setPage("profile");setWizard(0)}
 const journey=[["Persoonlijk",s.personal,"profile"],["Gezin",s.family,"profile"],["Werk",buyer.income?96:35,"profile"],["Eigen woning",s.home,"home"],["Financiën",s.financial,"profile"],["Documenten",s.docs,"documents"],["Woningen",91,"matches"],["Paspoort",68,"share"]];
 return <div className="app"><aside><div className="brand"><div className="mark">A</div><div><b>ATLAS</b><span>NEXT 2.3</span></div></div><button className="newUser" onClick={()=>setShowNew(true)}><Plus/> Nieuwe koper</button>{showNew&&<div className="newBox"><b>Start nieuw profiel</b><button onClick={()=>createProfile("starter")}>Starter</button><button onClick={()=>createProfile("doorstromer")}>Doorstromer met woning</button><button onClick={()=>createProfile("zzp")}>Ondernemer / ZZP</button><button onClick={()=>createProfile("blank")}>Leeg profiel</button></div>}<div className="journey">{journey.map(([name,sc,target],i)=><button key={name} onClick={()=>{setPage(target); if(target==="profile")setWizard(Math.min(i,5))}} className={page===target?"routebtn active":"routebtn"}><span className={sc>=80?"done":sc>=60?"busy":"todo"}>{sc>=80?"✓":i+1}</span><div><b>{name}</b><small>{sc}%</small></div></button>)}</div><nav>{[["cockpit",Compass,"Cockpit"],["profile",UserRound,"Gegevens"],["home",HousePlus,"Mijn woning"],["documents",UploadCloud,"Documenten"],["matches",Home,"Matches"],["coach",Bot,"Koopcoach"],["share",Share2,"Delen"]].map(([id,Icon,label])=><button key={id} onClick={()=>setPage(id)} className={page===id?"on":""}><Icon/> {label}</button>)}</nav></aside><main>{page==="cockpit"&&<Cockpit s={s} setPage={setPage} selected={selected} buyer={buyer}/>} {page==="profile"&&<Profile buyer={buyer} update={update} s={s} wizard={wizard} setWizard={setWizard}/>} {page==="home"&&<MyHome buyer={buyer} update={update} s={s} docs={docs} setDocs={setDocs}/>} {page==="documents"&&<Documents docs={docs} setDocs={setDocs} s={s}/>} {page==="matches"&&<Matches homes={homes.map(h=>adjustHome(h,s))} homeId={homeId} setHomeId={setHomeId} selected={selected} s={s}/>} {page==="coach"&&<Coach buyer={buyer} s={s} selected={selected} setPage={setPage}/>} {page==="share"&&<Share buyer={buyer} s={s} selected={selected}/>}</main></div>
}

function Cockpit({s,setPage,selected,buyer}){return <section><div className="hero"><div><span className="kicker">ATLAS Confidence Engine</span><h1>Goedemorgen {buyer.firstName}.</h1><p className="lead">Je bent vandaag <b>{s.atlas}% koopklaar</b>. De snelste winst zit in documenten, BKR-check en bevestiging van je woningwaarde.</p><div className="actions"><button onClick={()=>setPage("profile")}>Gegevens aanvullen</button><button className="secondary" onClick={()=>setPage("documents")}>Documenten uploaden</button></div></div><div className="scoreOrb"><span>Koopklaar</span><strong>{s.atlas}</strong><Bar value={s.atlas}/><small>Confidence: {s.confidence}%</small></div></div><div className="today"><Action title="Nieuwe koper toevoegen" points="Multi-profiel" text="Maak een starter, doorstromer of ZZP-profiel aan." icon={<Users/>}/><Action title="Document Vault afronden" points="+13 punten" text="Upload laatste 3 salarisstroken en woningdocumenten." icon={<FileText/>}/><Action title="Beste match vandaag" points={`${selected.match}% match`} text={`${selected.title} in ${selected.city}`} icon={<Home/>}/></div></section>}
function Action({title,points,text,icon}){return <article className="card">{icon}<Badge value={80}>{points}</Badge><h3>{title}</h3><p>{text}</p></article>}

function Profile({buyer,update,s,wizard,setWizard}){
 const tabs=["Persoonlijk","Gezin","Werk","Financiën","Woonwensen","Resultaat"];
 const showPension=buyer.age>=50||buyer.workStatus.includes("Pensioen")||buyer.workStatus.includes("Bijna");
 const strongPension=buyer.age>=57||buyer.workStatus.includes("Pensioen")||buyer.workStatus.includes("Bijna");
 return <section><Header kicker="Gegevens Wizard" title="Maak je ATLAS-profiel compleet." text="Meer detail per categorie. De score verandert live terwijl je invult."/><div className="wizardTabs">{tabs.map((t,i)=><button key={t} onClick={()=>setWizard(i)} className={wizard===i?"active":""}>{i+1}. {t}</button>)}</div><div className="wizardGrid"><div className="panel formPanel">{wizard===0&&<><h3>Persoonlijke gegevens</h3><div className="two"><Field label="Voornaam" value={buyer.firstName} onChange={v=>update("firstName",v)}/><Field label="Achternaam" value={buyer.lastName} onChange={v=>update("lastName",v)}/></div><div className="two"><Field label="Geboortedatum" type="date" value={buyer.birthDate} onChange={v=>update("birthDate",v)}/><Field label="Leeftijd koper" type="number" value={buyer.age} onChange={v=>update("age",v)}/></div>{showPension&&<div className={strongPension?"notice strong":"notice"}><Landmark/><div><b>{strongPension?"Pensioencheck aanbevolen":"Pensioen later relevant"}</b><p>Omdat een hypotheek kan doorlopen na pensioenleeftijd, kan toekomstig inkomen invloed hebben op je koopkans.</p></div></div>}<div className="two"><Select label="Burgerlijke staat" value={buyer.maritalStatus} onChange={v=>update("maritalStatus",v)} options={["Alleenstaand","Gehuwd","Geregistreerd partnerschap","Samenwonend","Gescheiden","Weduwe/weduwnaar"]}/><Select label="Vermogensregeling" value={buyer.maritalProperty} onChange={v=>update("maritalProperty",v)} options={["Niet van toepassing","Gemeenschap van goederen","Beperkte gemeenschap","Huwelijkse voorwaarden"]}/></div><Field label="Nationaliteit" value={buyer.nationality} onChange={v=>update("nationality",v)}/></>}
 {wizard===1&&<><h3>Gezinssituatie</h3><div className="toggleGrid"><Toggle label="Partner aanwezig" checked={buyer.partner} onChange={v=>update("partner",v)}/><Toggle label="Kinderen" checked={buyer.children} onChange={v=>update("children",v)}/><Toggle label="Co-ouderschap" checked={buyer.coParenting} onChange={v=>update("coParenting",v)}/><Toggle label="Alimentatie" checked={buyer.alimony} onChange={v=>update("alimony",v)}/></div>{buyer.partner&&<div className="two"><Field label="Naam partner" value={buyer.partnerName} onChange={v=>update("partnerName",v)}/><Field label="Leeftijd partner" type="number" value={buyer.partnerAge} onChange={v=>update("partnerAge",v)}/></div>}{buyer.children&&<div className="two"><Field label="Aantal kinderen" type="number" value={buyer.childCount} onChange={v=>update("childCount",v)}/><Field label="Leeftijden kinderen" value={buyer.childAges} onChange={v=>update("childAges",v)}/></div>}<Field label="Kinderopvang p/m" prefix="€" type="number" value={buyer.childcare} onChange={v=>update("childcare",v)}/></>}
 {wizard===2&&<><h3>Werk, inkomen & pensioen</h3><div className="two"><Select label="Werkstatus" value={buyer.workStatus} onChange={v=>update("workStatus",v)} options={["Vast contract","Tijdelijk contract","ZZP","DGA / eigen bedrijf","Bijna met pensioen","Pensioen","Uitzend / oproep","Anders"]}/><Field label="Werkgever" value={buyer.employer} onChange={v=>update("employer",v)}/></div><Field label="Functie" value={buyer.role} onChange={v=>update("role",v)}/><div className="two"><Field label="Bruto jaarinkomen" prefix="€" type="number" value={buyer.income} onChange={v=>update("income",v)}/><Field label="Partnerinkomen" prefix="€" type="number" value={buyer.partnerIncome} onChange={v=>update("partnerIncome",v)}/></div><div className="toggleGrid"><Toggle label="Vakantiegeld" checked={buyer.holidayPay} onChange={v=>update("holidayPay",v)}/><Toggle label="13e maand" checked={buyer.thirteenthMonth} onChange={v=>update("thirteenthMonth",v)}/><Toggle label="Proeftijd" checked={buyer.probation} onChange={v=>update("probation",v)}/></div><div className="two"><Field label="Bonus p/j" prefix="€" type="number" value={buyer.bonus} onChange={v=>update("bonus",v)}/><Field label="Overuren p/j" prefix="€" type="number" value={buyer.overtime} onChange={v=>update("overtime",v)}/></div>{showPension&&<div className="pensionBox"><h3>Pensioencheck</h3><div className="two"><Field label="Pensioenleeftijd" type="number" value={buyer.pensionAge} onChange={v=>update("pensionAge",v)}/><Field label="Verwacht pensioeninkomen p/j" prefix="€" type="number" value={buyer.pensionIncome} onChange={v=>update("pensionIncome",v)}/></div><div className="two"><Field label="Partnerpensioen p/j" prefix="€" type="number" value={buyer.partnerPension} onChange={v=>update("partnerPension",v)}/><Select label="Daalt inkomen na pensioen?" value={buyer.pensionDrop} onChange={v=>update("pensionDrop",v)} options={["Ja","Nee","Onbekend"]}/></div></div>}</>}
 {wizard===3&&<><h3>Financiële situatie</h3><div className="two"><Field label="Spaargeld" prefix="€" type="number" value={buyer.cash} onChange={v=>update("cash",v)}/><Field label="Beleggingen" prefix="€" type="number" value={buyer.investments} onChange={v=>update("investments",v)}/></div><div className="two"><Field label="Crypto" prefix="€" type="number" value={buyer.crypto} onChange={v=>update("crypto",v)}/><Field label="Studieschuld" prefix="€" type="number" value={buyer.studyDebt} onChange={v=>update("studyDebt",v)}/></div><div className="two"><Field label="Persoonlijke lening" prefix="€" type="number" value={buyer.loans} onChange={v=>update("loans",v)}/><Field label="Private lease p/m" prefix="€" type="number" value={buyer.leaseMonthly} onChange={v=>update("leaseMonthly",v)}/></div><div className="two"><Field label="Creditcard schuld" prefix="€" type="number" value={buyer.creditcard} onChange={v=>update("creditcard",v)}/><Select label="BKR-status" value={buyer.bkr} onChange={v=>update("bkr",v)} options={["Onbekend","Geen negatieve registratie","Positieve registratie","Negatieve registratie"]}/></div><a className="bkrBtn" href="https://www.bkr.nl/inloggen" target="_blank" rel="noreferrer"><ExternalLink size={17}/> Check BKR registratie</a><p className="small">Officiële controle buiten ATLAS. ATLAS bewaart alleen de status die jij invult of uploadt.</p></>}
 {wizard===4&&<><h3>Woonwensen</h3><Field label="Favoriete plaatsen" value={buyer.places} onChange={v=>update("places",v)}/><div className="two"><Field label="Zoekstraal km" type="number" value={buyer.radius} onChange={v=>update("radius",v)}/><Field label="Minimaal aantal kamers" type="number" value={buyer.rooms} onChange={v=>update("rooms",v)}/></div><div className="two"><Select label="Woningtype" value={buyer.homeType} onChange={v=>update("homeType",v)} options={["Appartement","Tussenwoning","Hoekwoning / gezinswoning","Twee-onder-een-kap","Vrijstaand","Nieuwbouw"]}/><Select label="Energielabel" value={buyer.energy} onChange={v=>update("energy",v)} options={["Geen voorkeur","A of beter","B of beter","C of beter"]}/></div><div className="toggleGrid"><Toggle label="Tuin" checked={buyer.garden} onChange={v=>update("garden",v)}/><Toggle label="Garage" checked={buyer.garage} onChange={v=>update("garage",v)}/></div></>}
 {wizard===5&&<><h3>Resultaat intake</h3><div className="resultCards"><Metric label="ATLAS Score" value={s.atlas}/><Metric label="Koopruimte" value={short(s.budget)}/><Metric label="Overwaarde" value={euro(s.equity)}/><Metric label="Documentstatus" value={s.docs+"%"}/></div><p>Volgende stap: upload ontbrekende documenten, check BKR en bevestig je woningwaarde.</p></>}
 <div className="wizardActions"><button className="secondary" disabled={wizard===0} onClick={()=>setWizard(Math.max(0,wizard-1))}>Terug</button><button onClick={()=>setWizard(Math.min(tabs.length-1,wizard+1))}>Volgende <ChevronRight size={16}/></button></div></div><LivePanel s={s}/></div></section>
}

function LivePanel({s}){return <aside className="livePanel"><h3>Live effect</h3><strong>{s.atlas}</strong><Badge value={s.atlas}>{s.atlas>=82?"Koopklaar":"Bijna koopklaar"}</Badge><Bar value={s.atlas}/><Metric label="Indicatieve bandbreedte" value={short(s.budget)}/><Metric label="Confidence" value={s.confidence+"%"}/><Metric label="Betrouwbaarheid woningwaarde" value={s.homeReliability+"%"}/><div className="tip"><Bot size={18}/> Nog nodig: BKR-check, taxatierapport en laatste 3 salarisstroken.</div></aside>}

function MyHome({buyer,update,s,docs,setDocs}){
 const woningDocs=docs.filter(d=>["Taxatierapport huidige woning","Energielabel rapport","WOZ-beschikking"].includes(d.name));
 const setDocVerified=(name)=>setDocs(docs.map(d=>d.name===name?{...d,status:"verified",progress:100}:d));
 return <section><Header kicker="Mijn Woning Engine" title="Vul je huidige woning in." text="ATLAS berekent overwaarde, inzetbare waarde, verkoopscenario en betrouwbaarheid van de woningwaarde."/><div className="homeEngine"><div className="panel"><h3>Adres & status</h3><Field label="Adres" value={buyer.address} onChange={v=>update("address",v)}/><Select label="Verkoopstatus" value={buyer.saleStatus} onChange={v=>update("saleStatus",v)} options={["Geen huidige woning","Nog niet verkocht","Binnenkort te koop","Te koop","Onder bod","Verkocht"]}/><div className="fakeMap"><Search/><p>Google Maps / BAG / WOZ demo-koppeling</p></div></div><div className="panel"><h3>Woningwaarde</h3><Field label="Geschatte woningwaarde" prefix="€" type="number" value={buyer.homeValue} onChange={v=>update("homeValue",v)}/><Field label="WOZ-waarde" prefix="€" type="number" value={buyer.woz} onChange={v=>update("woz",v)}/><Field label="Hypotheekrestant" prefix="€" type="number" value={buyer.mortgageLeft} onChange={v=>update("mortgageLeft",v)}/><Field label="Verkoopkosten" prefix="€" type="number" value={buyer.sellingCosts} onChange={v=>update("sellingCosts",v)}/></div><div className="valuation"><span>Vrije overwaarde</span><strong>{euro(s.equity)}</strong><small>Verwacht inzetbaar: {euro(s.usable)}</small><Metric label="Betrouwbaarheid woningwaarde" value={s.homeReliability+"%"}/><Metric label="Koopruimte met verkoop eerst" value={short(s.budget+45000)}/></div></div><div className="woningDocs"><h3>Woningdocumenten</h3><p>Deze documenten maken de overwaarde en woningwaarde betrouwbaarder.</p><div className="docMiniGrid"><DocMini title="Taxatierapport" text="Verhoogt betrouwbaarheid woningwaarde" status={docs.find(d=>d.name==="Taxatierapport huidige woning")?.progress||0} onClick={()=>setDocVerified("Taxatierapport huidige woning")}/><DocMini title="Energielabel rapport" text="Invloed op waarde, verkoopbaarheid en energielasten" status={docs.find(d=>d.name==="Energielabel rapport")?.progress||0} onClick={()=>setDocVerified("Energielabel rapport")}/><DocMini title="WOZ-beschikking" text="Optioneel, handig als extra onderbouwing" status={docs.find(d=>d.name==="WOZ-beschikking")?.progress||0} onClick={()=>setDocs([...docs,{id:Date.now(),name:"WOZ-beschikking",type:"Eigen woning",status:"verified",progress:100,impact:3}])}/></div></div></section>
}
function DocMini({title,text,status,onClick}){return <div className="docMini"><div className={status>=100?"miniIcon ok":"miniIcon miss"}>{status>=100?<CheckCircle2/>:<UploadCloud/>}</div><div><b>{title}</b><p>{status>=100?"Geüpload en gekoppeld":text}</p></div><button className={status>=100?"soft":"uploadBtn"} onClick={onClick}>{status>=100?"Bekijk":"Upload"}</button></div>}

function Documents({docs,setDocs,s}){
 function upload(id){setDocs(docs.map(d=>{if(d.id!==id)return d;if(d.required){const up=Math.min(d.required,(d.uploaded||0)+1);return{...d,uploaded:up,progress:Math.round(up/d.required*100),status:up===d.required?"verified":"review"}}return{...d,status:"verified",progress:100}}))}
 function review(id){setDocs(docs.map(d=>d.id===id?{...d,status:"review",progress:d.required?Math.max(d.progress,34):65}:d))}
 function remove(id){setDocs(docs.filter(d=>d.id!==id))}
 function add(){setDocs([...docs,{id:Date.now(),name:"Nieuw document",type:"Overig",status:"missing",progress:0,impact:2}])}
 const missing=docs.filter(d=>d.progress<100);
 return <section><Header kicker="Document Vault" title="Interactieve checklist." text="Duidelijke upload-, controle- en statusknoppen. Salarisstroken worden als set van 3 bijgehouden."/><div className="vaultTop"><div><h3>Je documentstatus is {s.docs}% compleet.</h3><p>Nog {missing.length} documenten tot een sterker ATLAS Paspoort.</p><Bar value={s.docs}/></div><button onClick={add}><Plus/> Document toevoegen</button></div><div className="docGrid">{docs.map(d=><div className="doc" key={d.id}><div className={"statusIcon "+(d.status==="verified"?"ok":d.status==="review"?"wait":"miss")}>{d.status==="verified"?<CheckCircle2/>:d.status==="review"?<Clock3/>:<AlertTriangle/>}</div><div><input value={d.name} onChange={e=>setDocs(docs.map(x=>x.id===d.id?{...x,name:e.target.value}:x))}/><small>{d.type} · {d.required?`${d.uploaded||0} van ${d.required} geüpload`:d.status==="verified"?"Geverifieerd":d.status==="review"?"AI controle bezig":"Ontbreekt"}</small><Bar value={d.progress}/></div><Badge value={d.progress}>{d.progress}%</Badge>{d.status==="verified"?<button className="soft"><Eye size={16}/> Bekijk</button>:<button onClick={()=>upload(d.id)}><UploadCloud size={16}/> Upload</button>}{d.status==="missing"&&<button className="soft" onClick={()=>review(d.id)}>AI check</button>}<button className="iconbtn light" onClick={()=>remove(d.id)}><Trash2 size={17}/></button></div>)}</div></section>
}

function Matches({homes,homeId,setHomeId,selected,s}){return <section><Header kicker="Woning Match" title="Funda toont huizen. ATLAS toont welke huizen slim zijn." text="Elke woning krijgt een Match, Koopkans, financieringskans en context."/><div className="matchGrid"><div className="cards">{homes.map(h=><button key={h.id} className={homeId===h.id?"matchCard active":"matchCard"} onClick={()=>setHomeId(h.id)}><img src={h.img}/><div><Badge value={h.match}>{h.match}% match</Badge><h3>{h.title}</h3><p>{h.city} · {euro(h.price)}</p></div></button>)}</div><div className="propertyDetail"><img src={selected.img}/><div className="propertyBody"><Badge value={selected.match}>{selected.match}% ATLAS Match</Badge><h2>{selected.title}</h2><p><MapPin/> {selected.city} · energielabel {selected.label}</p><div className="meters"><Metric label="Prijs" value={euro(selected.price)}/><Metric label="Jouw bandbreedte" value={short(s.budget)}/><Metric label="Koopkans" value={`${selected.confidence}%`}/><Metric label="Maandlast" value={euro(selected.monthly)}/></div><div className="why"><h3>Waarom deze score?</h3>{selected.why.map(w=><p key={w}>✓ {w}</p>)}</div></div></div></div></section>}

function Coach({s,selected,setPage}){
 const[messages,setMessages]=useState([{from:"atlas",text:"Waar wil je hulp bij? Kies een vraag of typ zelf iets."}]);
 const[input,setInput]=useState("");
 const answers={
  "Kan ik deze woning kopen?":`${selected.title} heeft nu ${selected.confidence}% koopkans. Je bandbreedte is ${short(s.budget)}. De grootste onzekerheid zit in documenten en woningwaarde onderbouwing.`,
  "Wat moet ik nu doen?":"Upload de laatste 3 salarisstroken, check je BKR-registratie en voeg taxatierapport + energielabel rapport toe. Dat verhoogt je ATLAS Confidence het snelst.",
  "Waarom is mijn score zo?":`Je ATLAS Score is ${s.atlas}. Documentstatus ${s.docs}%, woningwaarde betrouwbaarheid ${s.homeReliability}% en financiële score ${s.financial}% bepalen nu vooral je score.`,
  "Hoe verhoog ik mijn koopkans?":"Rond Document Vault af, bevestig de woningwaarde met een taxatierapport en verlaag waar mogelijk lease/leningen. Daarna worden meer woningen realistisch.",
  "Welke documenten ontbreken?":"Nog belangrijk: laatste 3 salarisstroken, taxatierapport huidige woning, energielabel rapport en eventuele BKR-onderbouwing."
 };
 function ask(q){setMessages(m=>[...m,{from:"user",text:q},{from:"atlas",text:answers[q]||"Ik zou eerst je documenten en woningwaarde afronden. Daarna kan ATLAS betrouwbaarder bepalen welke woningen echt haalbaar zijn."}])}
 function send(){if(!input.trim())return;ask(input);setInput("")}
 return <section><Header kicker="ATLAS Koopcoach" title="Je persoonlijke koopcoach." text="Geen statische kaartjes meer. Een guided chat die reageert op je profiel, documenten en woningmatch."/><div className="chatShell"><div className="quick">{Object.keys(answers).map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div><div className="chatBox">{messages.map((m,i)=><div key={i} className={"msg "+m.from}>{m.from==="atlas"&&<Bot size={18}/>}<p>{m.text}</p></div>)}</div><div className="chatActions"><button className="secondary" onClick={()=>setPage("documents")}>Ga naar documenten</button><button className="secondary" onClick={()=>setPage("home")}>Ga naar mijn woning</button><button className="secondary" onClick={()=>setPage("matches")}>Bekijk matches</button></div><div className="chatInput"><input placeholder="Typ je vraag aan ATLAS..." value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()}/><button onClick={send}><Send size={17}/> Verstuur</button></div></div></section>
}

function Share({buyer,s,selected}){return <section><Header kicker="Deel mijn ATLAS" title="Live paspoort voor de makelaar." text="Geen BSN. Geen loonstroken. Wel vertrouwen."/><div className="shareGrid"><div className="livePassport"><LockKeyhole/><h2>ATLAS Passport</h2><p>{buyer.firstName} {buyer.lastName}</p><strong>{s.confidence}</strong><Badge value={s.confidence}>Confidence</Badge></div><div className="shareFacts"><Fact icon={<ShieldCheck/>} label="Identiteit" value="Geverifieerd"/><Fact icon={<FileText/>} label="Documenten" value={`${s.docs}% compleet`}/><Fact icon={<HousePlus/>} label="Overwaarde" value={euro(s.equity)}/><Fact icon={<Home/>} label="Woning" value={selected.title}/><Fact icon={<Send/>} label="Advies" value="Plan bezichtiging"/></div></div></section>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><b>{value}</b></div>}
function Fact({icon,label,value}){return <div className="fact">{icon}<span>{label}</span><b>{value}</b></div>}

createRoot(document.getElementById("root")).render(<App/>);
